name: "Bug report"
description: "File a bug report to help us improve."
labels: ["bug-report"]
assignees:
  - leekelleher
body:
- type: markdown
  attributes:
    value: |
      **Note: for support questions, please use the [Umbraco Community forum](https://our.umbraco.com)**. This repository's issues are reserved for bug reports and feature requests.
- type: input
  id: "contentmentVersion"
  attributes:
    label: "Which Contentment version are you using?"
    description: "If you are unsure, we'll assume it's the latest version."
  validations:
    required: true
- type: input
  id: "umbracoVersion"
  attributes:
    label: "Which Umbraco version are you using? For example: 13.0.2 - don't just write v13"
    description: "Use the help icon in the Umbraco backoffice to find the version you're using."
  validations:
    required: true
- type: textarea
  id: "summary"
  attributes:
    label: "Bug summary"
    description: "Write a summary of the bug. Remember that you can format code and logs nicely with the `<>` button"
    placeholder: >
      
      Try to pinpoint it as much as possible.
      
      Try to state the actual problem, and not just what you think the solution might be.
  validations:
    required: true
- type: textarea
  id: "reproduction"
  attributes:
    label: "Steps to reproduce"
    description: "How can we reproduce the problem on a clean Contentment + Umbraco install?"
    placeholder: >
      
      Please include any links, screenshots, stack-traces, etc.
  validations:
    required: true
- type: textarea
  id: "result"
  attributes:
    label: "Expected result / actual result"
    description: "What did you expect that would happen on your Umbraco site and what is the actual result of the above steps?"
    placeholder: >
      
      Describe the intended/desired outcome after you did the steps mentioned.
      
      Describe the behaviour of the bug
- type: checkboxes
  id: umbracoModelsBuilder
  attributes:
    label: Do you have Umbraco ModelsBuilder enabled?
    description: "Select only if applicable."
    options:
      - label: Yes, it is enabled.
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
